Sandbox CSS
near/bos-web-engine pull request #255
Opened 2024-02-07 00:08 UTC by calebjacob

Closes: https://github.com/near/bos-web-engine/issues/234
Closes: https://github.com/near/bos-web-engine/issues/244

- Updated template files to use import syntax for `useState()` example 
- Implements basic support for CSS in the sandbox
- Correctly pulling down source code and CSS from Social DB
- Rendering gateway with actual theme colors (hard coded to a dark theme for the short term)

NOTE: There's currently an open bug related to adding and then removing a CSS property: https://github.com/near/bos-web-engine/issues/229

The styles look a little rough right now on the gateway demos, but we'll clean it up in a future PR: https://github.com/near/bos-web-engine/issues/240

I need to sync up with @heycorwin soon to figure out our plan for pulling in the official NEAR branded theme and exposing that through our `<Theme>` CSS variables.

2024-02-07 00:31 UTC, mpeterdev requested changes
(UX/UI only review)

Looks great! I am happy with how the linked files came out

One bug: On load for a new user, the style file for HelloWorld is focused by default

2024-02-07 00:44 UTC, calebjacob commented
Thanks! Good catch @mpeterdev - I forgot to update a hardcoded value from when I was first starting to implement the changes. Got that fixed.

2024-02-08 21:34 UTC, andy-haynes approved these changes
Looks great! Thank you for cleaning up the old compiler interface ❤️

2024-02-08 21:48 UTC, mpeterdev approved these changes

2024-02-08 21:49 UTC, merged