Rework flags and bos-loader integration
near/bos-web-engine pull request #357
Opened 2024-03-08 18:03 UTC by mpeterdev

This PR is functionally complete, but awaiting further testing before final cleanup

- moved flag management to bottom panel
- overhauled bos-loader integration to leverage `useWebEngineSandbox` and consolidate our local development flows

in `apps/web/src/pages/[[...root]].tsx`
![Screenshot 2024-03-08 at 12 57 29 PM](https://github.com/near/bos-web-engine/assets/24904709/4c20b68f-07e7-448a-b042-8900af07d3cb)
it would be great if we could combine these into a single hook in the future with the sandbox features as a config option

## UI
- icon in header appears when a bos-loader url is set and shows the URL in a tooltip on hover
- row for flags at top of bottom panel. `showContainerBoundaries` can now be toggled without reload
  - if `showContainerBoundaries` is provided in the URL, that overrides the flag

![pr](https://github.com/near/bos-web-engine/assets/24904709/2e644c7c-f1d5-454e-9acd-864fcac4e4b4)

2024-03-08 23:04 UTC, andy-haynes requested changes
Looks great, nice consolidation!

Scrolling doesn't work for me, either in the code window or within the Components. That's the only blocker I can see.

How much work would it be to convert the bottom panel to tabs? Flags/config could be one, and code could have a dedicated tab. Then I have a clean way to add messages back 😄

> if `showContainerBoundaries` is provided in the URL
I'm not opposed to just killing this URL param...

2024-03-11 15:38 UTC, calebjacob commented
Nice, love the new UX! Like Andy said, there are some issues with scrolling that need work.

2024-03-11 15:55 UTC, pavelisnear commented on apps/web/src/components/Inspector.module.css
> +  flex-direction: row;
Looks like we could remove this line, since this is a default value for the `flex-direction`.

2024-03-15 20:37 UTC, mpeterdev commented
> I'm not opposed to just killing this URL param...

it's helpful so that we can automatically enable it when sending developers to the trust demo

2024-03-19 00:12 UTC, mpeterdev commented
This is ready to go

Updated UI:
<img width="1135" alt="Screenshot 2024-03-18 at 8 10 05 PM" src="https://github.com/near/bos-web-engine/assets/24904709/01b9f718-da8a-4f55-a578-2344199518ea">
<img width="1133" alt="Screenshot 2024-03-18 at 8 10 18 PM" src="https://github.com/near/bos-web-engine/assets/24904709/fe53535e-fee4-4f85-b08b-4ae8574f08a8">
<img width="391" alt="Screenshot 2024-03-18 at 8 10 44 PM" src="https://github.com/near/bos-web-engine/assets/24904709/8df8fa84-3112-442c-aa49-7e9406767ac1">
<img width="391" alt="Screenshot 2024-03-18 at 8 10 54 PM" src="https://github.com/near/bos-web-engine/assets/24904709/a5ab5dcd-ae51-4c3e-a2ea-a0e7cbdf1514">

2024-03-20 18:14 UTC, andy-haynes approved these changes
Looks great, nice work!

2024-03-20 18:24 UTC, merged